---

# Install newest stable version of OpenSCAP.
# Package openscap-utils provides oscap.ssh (not needed on remote machines).

- name: Add OpenSCAP yum repo
  copy: src=openscapmaint-openscap-latest-epel-7.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: Install OpenSCAP packages on all machines.
  yum: pkg="{{ item }}" state=installed
  with_items:
    - openscap-scanner
    - openscap-utils

# If oscap_user is defined, create the account and grant it sudo capability.
# FIXME: Use a templated sudoers.d file so oscap_user can be insserted.

- name: Create oscap-user account on all machines.
  user: name="{{ oscap_user }}"
  when: oscap_user is defined

- name: Enable oscap-user to run openscap scanner as root.
  copy: src="99-{{ oscap_user }}"
        dest="/etc/sudoers.d/99-{{ oscap_user }}"
        owner=root group=root mode=0640
        force=no
  when: oscap_user is defined
